using ARMI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using ARMI.Helpers;

namespace ARMI.Data.Seed
{
    //Sources of information
    //https://github.com/RetroPie/RetroPie-Setup/wiki/Supported-Systems
    //https://gamesdb.launchbox-app.com/
    public static class SystemExtension
    {
        public static void EnsureSeedSystemData(this ApplicationDbContext context)
        {
            if (!context.AllMigrationsApplied()) return;
            if (!context.Systems.Any()) //Add them all since none exists
            {
                context.AddRange(PlatformList);
                context.SaveChanges();
            }
            else
            {
                //add the ones not present and overwrite properties on the ones match but do not delete any no match
                var platforms = context.Systems;
                foreach (var s in PlatformList)
                {
                    var d = platforms.FirstOrDefault(i => i.RomFolder == s.RomFolder);
                    if (d != null)
                    {
                        
                        d.Controllers = s.Controllers;
                        d.Cpu = s.Cpu;
                        d.Description = s.Description;
                        d.Developer = s.Developer;
                        d.Display = s.Display;
                        d.Graphics = s.Graphics;
                        d.Manufacturer = s.Manufacturer;
                        d.Name = s.Name;
                        d.Media = s.Media;
                        d.Memory = s.Memory;
                        d.ReleaseDate = s.ReleaseDate;
                        d.Sound = s.Sound;
                        d.ImageName = s.ImageName;
                    }
                    else
                    {
                        context.Add(s);
                    }
                }
                context.SaveChanges();
            }
        }

        public static readonly IEnumerable<Models.System> PlatformList =
            new List<Models.System>
            {
                new Models.System
                {
                    Name = "Arcade",
                    RomFolder = "arcade",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "arcade",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "3DO Interactive Multiplayer",
                    RomFolder = "3do",
                    Controllers = "1 (8 via daisy-chain)",
                    Cpu = "32-bit RISC ARM60",
                    Developer = "3DO Company",
                    Display = "320x240 and 640x480",
                    Graphics = "Custom",
                    ImageName = "3do",
                    Manufacturer ="Panasonic",
                    Media = "CD-ROM",
                    Memory = "2 MB main RAM and 1 MB video RAM",
                    ReleaseDate = "October 4, 1993; JP: March 20, 1994; EU: June 11, 1994",
                    Sound = "	16-bit stereo",
                    FileExtensions = ".iso",
                    Wiki = "https://en.wikipedia.org/wiki/Amiga",
                    Description = "The 3DO Interactive Multiplayer (often called simply 3DO) is a video game console originally produced by Panasonic in 1993. Further renditions of the hardware were released in 1994 by Sanyo and Goldstar. The consoles were manufactured according to specifications created by The 3DO Company, and were originally designed by Dave Needle and RJ Mical of New Technology Group. The system was conceived by entrepreneur and Electronic Arts founder Trip Hawkins."
                },
                new Models.System
                {
                    Name = "Commodore Amiga",
                    RomFolder = "amiga",
                    Controllers = "Keyboard, Mouse, 2 joysticks",
                    Cpu = "	Motorola 680x0 @ ≈7 MHz & higher",
                    Developer = "Commodore",
                    Display = "1024x800 NTSC or 1024x1024 PAL",
                    Graphics = "AGA chipset",
                    ImageName = "amiga",
                    Manufacturer ="Commodore International",
                    Media = "3.5\" disc",
                    Memory = "256 kilobytes and higher, expandable",
                    ReleaseDate = "July 23, 1985",
                    Sound = "4-channel",
                    FileExtensions = ".adf .adz .dms .exe .rp9 .zip",
                    Wiki = "https://en.wikipedia.org/wiki/Amiga",
                    Description = "The Amiga is a family of personal computers introduced by Commodore in 1985. The original model was part of a wave of 16- and 32-bit computers that featured 256 KB or more of RAM, mouse-based GUIs, and significantly improved graphics and audio over 8-bit systems."
                },
                new Models.System
                {
                    Name = "Amstrad CPC",
                    RomFolder = "amstradcpc",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "amstradcpc",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".cpc .dsk",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Apple II",
                    RomFolder = "apple2",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "apple2",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".dsk",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Atari 2600",
                    RomFolder = "atari2600",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "atari2600",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".7z .a26 .bin .gz .rom .zip",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Atari 5200",
                    RomFolder = "atari5200",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "atari5200",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".7z .a52 .atr .bas .bin .car .dcm .xex .xfd .zip .atr.gz .xfd.gz",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Atari 7800",
                    RomFolder = "atari7800",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "atari7800",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".7z .a78 .bin .zip",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Atari Jaguar",
                    RomFolder = "atarijaguar",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "atarijaguar",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".7z .a78 .bin .zip",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Atari Lynx",
                    RomFolder = "atarilynx",
                    Controllers = "",
                    Cpu = "WDC 65SC02",
                    Developer = "Epyx Atari Corporation",
                    Display = "",
                    Graphics = "160 × 102 standard resolution (16,320 addressable pixels)",
                    ImageName = "atarilynx",
                    Manufacturer ="	Atari Corporation",
                    Media = "ROM cartridge",
                    Memory = "",
                    ReleaseDate = "September 1, 1989",
                    Sound = "",
                    FileExtensions = ".7z .lnx .zip",
                    Wiki = "",
                    Description = "The Atari Lynx is a 16-bit handheld game console that was released by Atari Corporation in September 1989 in North America, and in Europe and Japan in 1990. It was the world's first handheld electronic game with a color LCD. It was also notable for its advanced graphics and ambidextrous layout. The Lynx competed with the Game Boy (released two months earlier), as well as the Game Gear and TurboExpress, both released the following year. It was discontinued in 1996."
                },
                new Models.System
                {
                    Name = "Atari ST STE TT Falcon",
                    RomFolder = "atarist",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "atarist",
                    Manufacturer ="",
                    Media = "",
                    Memory = "512 KBs (512×210 bytes) to 4 MB (4×220 bytes)",
                    ReleaseDate = "June 1985",
                    Sound = "",
                    FileExtensions = ".st .stx .msa .img .rom .raw .ipf .ctr",
                    Wiki = "",
                    Description = "The Atari ST is a line of home computers from Atari Corporation and the successor to the Atari 8-bit family. The initial ST model, the 520ST, saw limited release in April–June 1985 and was widely available in July. The Atari ST is the first personal computer to come with a bitmapped color GUI, using a version of Digital Research's GEM released in February 1985. The 1040ST, released in 1986, is the first personal computer to ship with a megabyte of RAM in the base configuration and also the first with a cost-per-kilobyte of less than US$1."
                },
                new Models.System
                {
                    Name = "Tandy Colour Computer (Coco)",
                    RomFolder = "coco",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "coco",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "1980",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "https://en.wikipedia.org/wiki/TRS-80_Color_Computer",
                    Description = "The RadioShack TRS-80 Color Computer is a line of home computers based on the Motorola 6809 processor. The Tandy Color Computer line started in 1980 with what is now called the CoCo 1 and ended in 1991 with the more powerful CoCo 3"
                },
                new Models.System
                {
                    Name = "Colecovision",
                    RomFolder = "coleco",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "coleco",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Commodore 64",
                    RomFolder = "c64",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "c64",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".crt .d64 .g64 .t64 .tap .x64 .zip .prg",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Daphne",
                    RomFolder = "daphne",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "daphne",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = ".daphne",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Nintendo Famicom Disk System",
                    RomFolder = "fds",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "256x240",
                    Graphics = "",
                    ImageName = "fds",
                    Manufacturer ="",
                    Media = "",
                    Memory = "Proprietary floppy disk",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "FinalBurn Alpha",
                    RomFolder = "arcade fba neogeo",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "fba",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "GameCube",
                    RomFolder = "gc",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "gc",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Game & Watch",
                    RomFolder = "gameandwatch",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "gameandwatch",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Game Boy Color",
                    RomFolder = "gbc",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "gbc",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Game Boy Advance",
                    RomFolder = "gba",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "gba",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Intellivision",
                    RomFolder = "intellivision",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "intellivision",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Macintosh",
                    RomFolder = "macintosh",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "macintosh",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "MAME",
                    RomFolder = "arcade mame-mame4all mame-libretro mame-advmame",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "mame",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sega Master System",
                    RomFolder = "mastersystem",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "mastersystem",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sega CD",
                    RomFolder = "segacd",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "segacd",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sega Mega Drive/Genesis",
                    RomFolder = "megadrive",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "megadrive",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "MESS",
                    RomFolder = "coleco crvision arcadia nes gameboy svmu",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "mess",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "MSX",
                    RomFolder = "msx",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "msx",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Neo Geo",
                    RomFolder = "neogeo",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "neogeo",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Neo Geo Pocket",
                    RomFolder = "ngp",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "ngp",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Neo Geo Pocket Color",
                    RomFolder = "ngpc",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "ngpc",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Nintendo 64",
                    RomFolder = "n64",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "n64",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Nintendo DS",
                    RomFolder = "nds",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "nds",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Nintendo Entertainment System",
                    RomFolder = "nes",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "nes",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "OpenBOR",
                    RomFolder = "openbor",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "openbor",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Oric",
                    RomFolder = "oric",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "oric",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "PC (DOS)",
                    RomFolder = "pc",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "pc",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "PC 8800",
                    RomFolder = "pc88",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "pc88",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "PC 9800",
                    RomFolder = "pc98",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "pc98",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "PC Engine",
                    RomFolder = "pcengine",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "pcengine",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sony Playstation",
                    RomFolder = "psx",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "psx",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sony Playstation 2",
                    RomFolder = "ps2",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "ps2",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Pokemon Mini",
                    RomFolder = "pokemini",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "pokemini",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sony PlayStation Portable (PSP)",
                    RomFolder = "psp",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "psp",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "ResidualVM",
                    RomFolder = "residualvm",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "residualvm",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sam Coupe",
                    RomFolder = "samcoupe",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sega Saturn",
                    RomFolder = "saturn",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "ScummVM",
                    RomFolder = "scummvm",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sega 32X",
                    RomFolder = "sega32x",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "SG 1000",
                    RomFolder = "sg-1000",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sharp X1",
                    RomFolder = "x1",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sharp X68000",
                    RomFolder = "x68000",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Super Nintendo Entertainment System",
                    RomFolder = "snes",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "TI 99",
                    RomFolder = "ti99",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "TRS 80",
                    RomFolder = "trs-80",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Vectrex",
                    RomFolder = "vectrex",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "VideoPac Odyssey 2",
                    RomFolder = "videopac",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Virtual Boy",
                    RomFolder = "virtualboy",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Nintendo Wii",
                    RomFolder = "wii",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "WonderSwan",
                    RomFolder = "wonderswan",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "WonderSwan Color",
                    RomFolder = "wonderswancolor",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sinclair ZX81",
                    RomFolder = "zx81",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
                new Models.System
                {
                    Name = "Sinclair ZX Spectrum",
                    RomFolder = "zxspectrum",
                    Controllers = "",
                    Cpu = "",
                    Developer = "",
                    Display = "",
                    Graphics = "",
                    ImageName = "",
                    Manufacturer ="",
                    Media = "",
                    Memory = "",
                    ReleaseDate = "",
                    Sound = "",
                    FileExtensions = "",
                    Wiki = "",
                    Description = ""
                },
            };
    }
}

//new Models.System
//{
//    Name = "",
//    RomFolder = "",
//    Controllers = "",
//    Cpu = "",
//    Developer = "",
//    Display = "",
//    Graphics = "",
//    Manufacturer ="",
//    Media = "",
//    Memory = "",
//    ReleaseDate = "",
//    Sound = "", 
//    FileExtensions = "",
//    Wiki = "",
//    Description = ""
//}