theme: jekyll-theme-minimal-armi
title: Arcade Rom Management Interface
description: This tool will help you setup and manage your retro gaming roms, emulators, frontends etc.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Drivers
    url: drivers
  - title: Emulators
    url: emulators
  - title: Hotkeys
    url: hotkeys
  - title: Tools
    url: tools
  - title: Developer Guide
    url: developer-guide
